# Generated by Django 5.0.4 on 2024-05-08 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BdDadosdeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=50, verbose_name='Fornecedor/Serviço')),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=15)),
                ('link', models.URLField()),
                ('level', models.CharField(choices=[('gerente', 'Gerência'), ('efetivo', 'efetivo'), ('estagiario', 'Estagiário')], max_length=15)),
                ('atualizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Atualização')),
            ],
        ),
    ]
