# Generated by Django 5.0.4 on 2024-05-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irradiacao',
            old_name='irr',
            new_name='irradiação',
        ),
    ]
