# Generated by Django 5.0.4 on 2024-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_rename_irr_irradiacao_irradiação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irradiacao',
            name='irradiação',
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_abr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_ago',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_dez',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_fev',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_jan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_jul',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_jun',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_mai',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_mar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_media',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_nov',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_out',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr_set',
            field=models.FloatField(default=0),
        ),
    ]
