# Generated by Django 5.0.4 on 2024-05-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_remove_irradiacao_irradiação_irradiacao_irr_abr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradiacao',
            name='irradiação',
            field=models.TextField(default=0),
        ),
    ]
