# Generated by Django 5.0.4 on 2024-05-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_irradiacao_irradiação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradiacao',
            name='irradiação',
            field=models.TextField(),
        ),
    ]
