# Generated by Django 5.0.4 on 2024-05-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_alter_irradiacao_irradiação'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradiacao',
            name='data_atualização',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
    ]
