# Generated by Django 5.0.4 on 2024-05-05 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_irradiacao_data_atualização'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradiacao',
            name='data_atualização',
            field=models.DateField(verbose_name=datetime.date(2024, 5, 5)),
        ),
    ]
