# Generated by Django 5.0.4 on 2024-05-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_alter_irradiacao_data_atualização'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irradiacao',
            old_name='data_atualização',
            new_name='atualização',
        ),
    ]
