# Generated by Django 5.0.4 on 2024-05-05 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0012_alter_irradiacao_atualização'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradiacao',
            name='atualização',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
