# Generated by Django 5.0.4 on 2024-05-05 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0013_alter_irradiacao_atualização'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancodepreços',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualização', models.DateField(default=django.utils.timezone.now)),
                ('inversor', models.TextField()),
                ('módulo', models.TextField()),
                ('potência', models.IntegerField()),
                ('preço', models.FloatField(default=0)),
                ('fornecedor', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
