# Generated by Django 5.0.4 on 2024-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0014_bancodepreços'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irradiacao',
            name='estado',
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='uf',
            field=models.CharField(default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bancodepreços',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bancodepreços',
            name='preço',
            field=models.FloatField(),
        ),
    ]
