# Generated by Django 5.0.4 on 2024-05-05 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0015_remove_irradiacao_estado_irradiacao_uf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancodeprecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Última Atualização')),
                ('inversor', models.TextField()),
                ('modulo', models.TextField(verbose_name='Módulo')),
                ('potencia', models.IntegerField(verbose_name='Potência')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('fornecedor', models.TextField()),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bancodepreços',
        ),
        migrations.RemoveField(
            model_name='irradiacao',
            name='atualização',
        ),
        migrations.RemoveField(
            model_name='irradiacao',
            name='irradiação',
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='atualizacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='irradiacao',
            name='irr',
            field=models.TextField(blank=True, verbose_name='Irradiação'),
        ),
    ]
