# Generated by Django 5.0.4 on 2024-05-06 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0016_bancodeprecos_delete_bancodepreços_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bd_Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('micro', 'Micro Inversor'), ('inversor', 'Inversor')], max_length=10)),
                ('marca', models.CharField(max_length=300)),
                ('modelo', models.TextField()),
                ('potencia', models.PositiveIntegerField()),
                ('atualizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Bd_Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=300)),
                ('modelo', models.TextField()),
                ('potencia', models.PositiveIntegerField()),
                ('eficiencia', models.FloatField()),
                ('area', models.FloatField()),
                ('peso', models.FloatField()),
                ('atualizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Última Atualização')),
            ],
        ),
        migrations.AddField(
            model_name='bancodeprecos',
            name='qtdInversor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bancodeprecos',
            name='qtdModulos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bancodeprecos',
            name='inversor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.bd_inversor'),
        ),
        migrations.AlterField(
            model_name='bancodeprecos',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.bd_modulos'),
        ),
        migrations.CreateModel(
            name='Bd_propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=50)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Proposta')),
                ('consumo', models.PositiveIntegerField(verbose_name='Consumo Faturado')),
                ('ligacao', models.CharField(choices=[('mono', 'monofásico'), ('tri', 'trifásico')], max_length=5)),
                ('equipamentos', models.FloatField(verbose_name='Equipamentos Elétricos')),
                ('impostos', models.FloatField()),
                ('equipe', models.FloatField(verbose_name='Custo com Equipe de execução')),
                ('captador', models.FloatField(verbose_name='Porcentagem do captador')),
                ('lucro', models.FloatField(verbose_name='Lucro Previsto')),
                ('valor_final', models.FloatField(verbose_name='Valor final do Projeto')),
                ('preco_sugerido', models.FloatField(verbose_name='Preço Sugerido')),
                ('payback', models.TextField(verbose_name='Retorno Financeiro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_irr', to='orcamentos.irradiacao')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_irr', to='orcamentos.irradiacao')),
            ],
        ),
    ]
