# Generated by Django 5.0.4 on 2024-05-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0017_bd_inversor_bd_modulos_bancodeprecos_qtdinversor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancodeprecos',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bancodeprecos',
            name='qtdInversor',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Inversores'),
        ),
        migrations.AlterField(
            model_name='bancodeprecos',
            name='qtdModulos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Módulos'),
        ),
    ]
